//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestRMSQP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login
    {
        public int loginId { get; set; }
        public string login1 { get; set; }
        public string loginName { get; set; }
        public string Password { get; set; }
        public int appId { get; set; }
        public int custId { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
